### PR TITLE
Testing for Division Controller 

### PR DESCRIPTION
**Pull request by NaufalMuh11**
###  Desription

Membuat sebuah testing untuk DivisionController.

```
 POST /api/v1/divisions                                                                                                                    
      √ should be rejected if user not authenticated                                                                            
      √ should be rejected if name is not provided                                                                                 
      √ should return error if name exceeds max length                                                                            
      √ should create division successfully                                                                                      
    GET /api/v1/divisions                                                                                                                     
      √ should get all divisions successfully                                                                                      
    GET /api/v1/divisions?id=id_division                                                                                                      
      √ should be rejected if division not found                                                                                
      √ should get division by id successfully                                                                                  
    PUT /api/v1/divisions?id                                                                                                                  
      √ should be rejected if division not found                                                                                    
      √ should reject if name is not provided                                                                                   
      √ should update division by id successfully                                                                                 
    DELETE /api/v1/divisions?id                                                                                                               
      √ should be rejected if division not found                                                                                  
      √ should delete division by id successfully 
```

## Note
I need review and help to create tests to check the soft delete implementation.

### CODE REVIEW

**Review by nugrahaAdhitama — CHANGES_REQUESTED** [review]
# Code Review: Division Controller Test File

## General Observations
- **Repetitive Code**: Several blocks of code, like the authentication and request setup, are repeated across tests. This can lead to maintenance issues and unnecessary duplication.
- **Error Validation**: Some of the error handling logic is a bit too verbose and could be streamlined to make the tests more readable.
- **Test Timeout Configuration**: The custom timeout settings for each test (`60000`) seem to be over-configured. This could be avoided if not necessary for all tests.
- **Consistency**: While the tests themselves are well-written, some conventions, such as error message validation, are inconsistent across tests.
- **Test Purpose Clarity**: Some tests might benefit from clearer naming to better describe the expected behavior or conditions under which the test operates.

## Specific Feedback

### **Scope 1: Repetitive Setup and Token Authentication**
- **Issue**: The `authenticateUser` and `createDivision` functions are used repeatedly across tests, which increases code duplication and violates the DRY (Don't Repeat Yourself) principle.
- **Suggestion**: Move the repetitive functions like `authenticateUser` and `createDivision` to a `beforeAll` block where they can be initialized once and reused across multiple tests. This will reduce duplication and make your test cases more concise.

### **Scope 2: Repetitive Authorization Headers**
- **Issue**: In many places, the same headers (`Authorization` and `Cookie`) are manually set for each request. This redundancy could lead to potential errors when modifying these headers in the future.
- **Suggestion**: Refactor the code to centralize the header setup into a utility function. This function can take a token and return the appropriate headers, making it easier to adjust in case of changes and improve maintainability.

### **Scope 3: Verbose Error Validation**
- **Issue**: Error validation, such as checking for the existence of specific error messages, is too verbose and spread out in the tests, which reduces readability.
- **Suggestion**: Create a helper function for error message validation to handle common cases. This will make tests more concise, focused, and easier to understand.

### **Scope 4: Consistent Timeout Configuration**
- **Issue**: The `60000` timeout is explicitly set for each test, although this may not be necessary for all tests. It introduces potential confusion when reading the tests as to why this value is required for every test case.
- **Suggestion**: If long timeouts are only needed for specific tests, apply them only to those tests, and let other tests use the default timeout configuration. Otherwise, set a global timeout for the entire test suite if necessary.

### **Scope 5: Test Names Should Be More Descriptive**
- **Issue**: Some test names (e.g., "should be rejected if name is not provided") don't fully explain the condition or purpose behind the test, making the intent slightly unclear.
- **Suggestion**: Refactor the test names to be more explicit about the scenario being tested. For example, use "should return 500 when division name is not provided" for clarity and better understanding of the expected outcome.

## Conclusion
The test file generally adheres to unit testing principles with clear assertions, but improvements can be made to enhance readability, reduce duplication, and improve maintainability. DRY principles should be applied by refactoring repetitive logic such as authentication and header management into reusable functions. Simplifying error validation and ensuring consistent configuration for timeouts will further streamline the test suite. Lastly, more descriptive test names will provide better documentation for the test cases. These adjustments will make the tests easier to maintain, extend, and understand while aligning them better with best practices for unit testing and the SOLID principles.

**Comment by nugrahaAdhitama** [comment]
Revisi dulu @NaufalMuh11 . Baru nanti gw kasih tau buat testing soft delete nya kaya gimana. Thanks

**Comment by NaufalMuh11** [comment]
### Description

This pull request addresses several improvements to  test suite to enhance maintainability, readability, and consistency. The following changes have been made after review suggestion

Changes Include:
- Extracted and reused common authentication and request setup logic.
- Streamlined error handling logic.
- Adjusted test timeout configurations.
- Standardized conventions for error validation.
- Renamed tests for better clarity and consistency.

**Review by nugrahaAdhitama — CHANGES_REQUESTED** [review]
While the revision addresses several key points from the code review, such as reducing redundancy in setup and headers, there are still opportunities for improvement, particularly in testing, with a focus on soft deletion. Although the current tests are robust, incorporating functionality for soft deletion—where records are marked as deleted rather than permanently removed—would enhance the thoroughness of the CRUD operation tests. Adding tests for soft deletion will help ensure that data integrity is maintained and deletions are properly managed.

The revision shows a commendable effort in adhering to best practices by minimizing redundant code and improving readability. The use of helper functions to centralize setup and validation is a great step toward maintaining the codebase. However, to achieve complete test coverage, the inclusion of tests simulating soft deletion scenarios would be beneficial. This would ensure that deleted divisions are correctly marked as inactive without being removed from the database. These additional tests will strengthen the test suite's ability to handle real-world scenarios effectively and maintain data accuracy.

**Example of soft delete test:**
```
// Soft delete functionality test
const softDeleteDivision = async (headers, divisionId) => {
  return await request(app)
    .put(`/api/v1/divisions?id=${divisionId}&softDelete=true`)
    .set(headers)
    .send({ isDeleted: true });
};

describe('Soft Delete Division', () => {
  it('should mark a division as deleted instead of permanently deleting', async () => {
    const { headers } = await setupAuthHeaders();
    const divisionData = { name: 'Temporary Division' };
    
    // Create a new division
    const createRes = await createDivision(headers, divisionData);
    const divisionId = createRes.body.data.id;

    // Soft delete the division
    const softDeleteRes = await softDeleteDivision(headers, divisionId);

    validateSuccessResponse(softDeleteRes, 200, 200, 'Successfully Soft Deleted Division');
    
    // Verify that the division still exists in the database but marked as deleted
    const res = await request(app).get(`/api/v1/divisions?id=${divisionId}`).set(headers);
    expect(res.body.data.isDeleted).toBe(true);
  });
});

```

**Comment by nugrahaAdhitama** [comment]
Don't copy the code above right away, because it's just an example.

**Review by nugrahaAdhitama — CHANGES_REQUESTED** [review]
# Review
The current sot delete test does not fully align with the intended approach, as it lacks validation of the database status affter the deletion. The test simply checks whether the division is soft deleted but does not properly query the database to verify the `deleted_at` field is set correctly. Additionally, the `isSoftDeleted` check uses incorrect syntax by directly comparing the `divisionId` object instead o querying the database for the division data. To ensure accuracy, the test should fetch the division after deletion and confirm that the `deleted_at` field is not `null`.

**Example Code:**
```
const fetchDivisionById = async (headers, divisionId) => {
  return await request(app)
    .get(`/api/v1/divisions?id=${divisionId}`)
    .set(headers);
};

describe('Soft Delete Division', () => {
  it('should soft delete a division and mark it as deleted by setting deleted_at field', async () => {
    const { headers } = await setupAuthHeaders();
    const divisionData = { name: 'Division to be Soft Deleted' };

    // Create the division
    const createRes = await createDivision(headers, divisionData);
    const divisionId = createRes.body.data.id;

    // Soft delete the division
    const deleteRes = await deleteDivisionById(headers, divisionId);
    validateSuccessResponse(deleteRes, 200, 200, 'Successfully Delete Division');

    // Fetch the division to verify soft deletion
    const fetchRes = await fetchDivisionById(headers, divisionId);
    expect(fetchRes.body.data.deleted_at).not.toBe(null);
    expect(fetchRes.body.data.isDeleted).toBe(true);
  });
});
```

**Review by nugrahaAdhitama — APPROVED** [review]
Approved

**Pull request merged**
